# Generated by Django 4.2.30 on 2026-07-24 03:16

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tags', select_multiple_field.models.SelectMultipleField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('api', 'API'), ('web', 'Web'), ('db', 'Database'), ('async', 'Async'), ('orm', 'ORM'), ('sql', 'SQL')], max_length=50)),
                ('category', models.CharField(choices=[('tech', 'Tech'), ('tutorial', 'Tutorial')], max_length=20)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', select_multiple_field.models.SelectMultipleField(blank=True, choices=[('new', 'New'), ('sale', 'Sale'), ('popular', 'Popular'), ('limited', 'Limited')], max_length=30, null=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
