# Generated by Django 4.2.30 on 2026-07-24 03:23

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_test', '0002_taggeditem_delete_product_remove_article_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='optional_tags',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('new', 'New'), ('sale', 'Sale'), ('popular', 'Popular'), ('limited', 'Limited')], max_length=30, null=True),
        ),
    ]
