[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "django-select-multiple-field"
dynamic = ["version"]
description = "Select multiple choices in a single Django model field"
readme = "README.md"
license = {text = "BSD"}
authors = [
    {name = "Kelvin Wong", email = "code@kelvinwong.ca"}
]
keywords = ["select", "select multiple", "Django", "model-field", "Django-Select-Multiple-Field"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.2",
    "Intended Audience :: Developers",

    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Internet :: WWW/HTTP",
]
requires-python = ">=3.10"
dependencies = [
    "Django>=4.2",
]

[project.urls]
Homepage = "https://kelvinwong.ca/projects/django-select-multiple-field/"
Repository = "https://github.com/kelvinwong-ca/django-select-multiple-field"

[tool.hatch.version]
path = "select_multiple_field/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["select_multiple_field"]

[tool.hatch.publish.pypi]
repository = "pypi"

[tool.hatch.publish.test]
repository = "testpypi"

[tool.hatch.envs.default.scripts]
t = "python -m django test test_suite --settings=test_suite.settings_for_tests --verbosity=1"
i = "python -m django test pizzagigi forthewing orm_test --settings=test_projects.django42.django42.settings --verbosity=1"
tests = [
    "hatch run t",
    "hatch run i"
]

[tool.hatch.envs.release]
dependencies = [
    "django"
]

[tool.hatch.envs.release.scripts]
install = "pip install  --force-reinstall --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple django-select-multiple-field"

verify-release = [
    "hatch run release:install",
    "hatch run tests",
]

build-test = [
    "hatch run tests",
]

