[tox]
envlist =
    py310-dj42, py310-dj52,
    py311-dj42, py311-dj52,
    py312-dj42, py312-dj52, py312-dj60,
    py313-dj42, py313-dj52, py313-dj60,
    py314-dj52,             py314-dj60
    ; py314-djangomaster
pip_pre = True
isolated_build = true
parallel_show_output = true


[testenv]
deps =
    dj42: Django>=4.2,<4.3
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.1
    dj61: Django>=6.1,<6.2
commands =
    python -m django test test_suite --settings=test_suite.settings_for_tests --verbosity=1
    python -m django test pizzagigi forthewing orm_test --settings=test_projects.django42.django42.settings --verbosity=1
package = editable

[testenv:unit]
description = Run unit test suite
deps = Django>=4.2
commands =
    python -m django test test_suite --settings=test_suite.settings_for_tests --verbosity=1

[testenv:py314-djangomaster]
recreate = True
basepython = python3.14
package = editable
deps =
    https://github.com/django/django/zipball/master
commands =
    python -m django test test_suite --settings=test_suite.settings_for_tests --verbosity=1
    python -m django test pizzagigi forthewing orm_test --settings=test_projects.django42.django42.settings --verbosity=1
