# Generated by Django 4.2.22 on 2026-07-18 11:51

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', select_multiple_field.models.SelectMultipleField(choices=[('a', 'Anchovies'), ('b', 'Black olives'), ('c', 'Cheddar cheese'), ('e', 'Eggs'), ('pk', 'Pancetta'), ('p', 'Pepperoni'), ('P', 'Prosciutto crudo'), ('m', 'Mozzarella'), ('M', 'Mushrooms'), ('t', 'Tomato')], max_length=10)),
                ('dips', select_multiple_field.models.SelectMultipleField(blank=True, choices=[('r', 'Ranch'), ('b', 'Blue cheese'), ('h', 'Honey mustard')], max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
                'ordering': ['pk'],
            },
        ),
    ]
