# Generated by Django 4.2.25 on 2025-11-05 09:21

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', select_multiple_field.models.SelectMultipleField(choices=[('a', 'Anchovies'), ('b', 'Black olives'), ('c', 'Cheddar cheese'), ('e', 'Eggs'), ('pk', 'Pancetta'), ('p', 'Pepperoni'), ('P', 'Prosciutto crudo'), ('m', 'Mozzarella'), ('M', 'Mushrooms'), ('t', 'Tomato')], max_length=10)),
            ],
        ),
    ]
