# Generated by Django 4.2.22 on 2025-11-15 10:31

from django.db import migrations
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzagigi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['pk'], 'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizzas'},
        ),
        migrations.AddField(
            model_name='pizza',
            name='dips',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[('r', 'Ranch'), ('b', 'Blue cheese'), ('h', 'Honey mustard')], max_length=5, null=True),
        ),
    ]
